name: Deploy to Heroku

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: GitHub Action for Heroku
      uses: actions/heroku@1.0.0
      env:
        HEROKU_APP: link-adidas
