name: Publish to Heroku

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login
    - name: Add heroku:git
      run: heroku git:remote -a link-adidas
    - name: Push
      run: git push heroku master
