name: Deploy to Heroku

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - uses: actions/checkout@v2
      - name: Heroku Login
        env:
          EMAIL: ${{ secrets.HEROKU_EMAIL }}
          PASSWORD: ${{ secrets.HEROKU_PASSWORD }}
        run: ': >  ~/.netrc ; echo "machine api.heroku.com \n login $HEROKU_EMAIL \n  password $HEROKU_PASSWORD" >> ~/.netrc'
        run: heroku login
      - name: Deploy
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: 'link-adidas'
        if: github.ref == 'refs/heads/master' && job.status == 'success'
        run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master
