name: Deploy to Heroku

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      run: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/link-adidas.git $GITHUB_SHA:master
